### ISSUE TITLE
Unable to determine hardware version. I see: Hardware	: BCM2835

### ISSUE THREAD

**Issue by nitin7dc** [firsttris/mfrc522-rpi#1]
Getting below error 

Unable to determine hardware version. I see: Hardware : BCM2835
 - expecting BCM2708 or BCM2709

**Comment by firsttris** [comment]
which raspberry are you using?

seems to be related to "wiring-pi" unable to determine your raspberry pi version.

regards
Tristan

**Comment by nitin7dc** [comment]
Raspberry pi 3 Model B running raspbian-jessie-lite 4.9.16-v7

**Comment by firsttris** [comment]
Okay.. i researched you issue 

it seems to be related to the new Kernel Version 4.9

there is already an issue in the Wiring-Pi Module:
https://github.com/WiringPi/WiringPi-Node/issues/70

hopefully the will update Wiring-Pi soon..

or we have to switch to another GPIO library which is better maintained.

**Comment by nitin7dc** [comment]
thanks, i will try on older version of kernel.

**Comment by firsttris** [comment]
i changed to a fixed wiringpi library
https://github.com/firsttris/mfrc522-rpi/commit/20b2fe60b8da27912992e1bf425f290a1deefea7
should be working now on Kernel Version 4.9

**Comment by nitin7dc** [comment]
thanks, i will check and confirm.

**Comment by ameenmohamed** [comment]
4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

does not work for me

**Comment by ameenmohamed** [comment]
i used 1.2 snap shot and upgraded . iupdated etc then it worked for me 

<dependency>
			<groupId>com.pi4j</groupId>
			<artifactId>pi4j-core</artifactId>
			<version>1.2-SNAPSHOT</version>
		</dependency>

<repositories>
	<repository>
		<id>oss-snapshots-repo</id>
		<name>Sonatype OSS Maven Repository</name>
		<url>https://oss.sonatype.org/content/groups/public</url>
		<snapshots>
			<enabled>true</enabled>
			<updatePolicy>always</updatePolicy>
		</snapshots>
	</repository>
</repositories>

**Comment by mesutpiskin** [comment]
`java -Dpi4j.linking=dynamic ....`
