### ISSUE TITLE
MFRC522 not working on RPi 4

### ISSUE THREAD

**Issue by mgoeller** [firsttris/mfrc522-rpi#10]
Hi, I'm getting the following error using my SD card that works fine in a Raspberry Pi Model 3, if I put it into a Raspberry Pi Model 4:

`WARNING: Hardware auto-detect failed, running in raspi-3 mock mode` 

And consequently the card detection does not work. Any idea what this could be related to?
Thanks

**Comment by firsttris** [comment]
could you update the dependency "rpio": "^1.0.13" to 1.2.2 and check if it works ?

**Comment by firsttris** [comment]
@mgoeller could you check?

**Comment by mgoeller** [comment]
Thank you, the RPi is in another home. I tried to update the dependency, now the error doesnt show anymore but the card reader is still not working. How can I debug?

**Comment by firsttris** [comment]
generally by running the examples. i mean you could add some console.log here and there. that would be a very easy approach vor debugging.

**Comment by mgoeller** [comment]
Finally got it to work. Unimaginable but the cables were the problem! Really strange that the same cables and the same MFRC522 module were working with a RPi3 but not a 4. Changed the cables and suddenly all worked. Thank you!
