### ISSUE TITLE
Cannot get continuous read

### ISSUE THREAD

**Issue by Dermiste** [firsttris/mfrc522-rpi#2]
Hi,

I am running the read.js script on the test folder, and it seems I cannot get a solid card detection.
When there is no card I can trace that using the following code:
```
    //# Scan for cards
    let response = mfrc522.findCard();
    if (!response.status) {
        console.log("NOT detected");
        console.log(" ### ");
        return;
    }
```
But when I let my tag on the reader I cannot get a solid read, instead I get "NOT DETECTED", then it works and I get the tag info ( a read ), then "NOT DETECTED" again, then it works again ... etc. It keeps going on and off like that.

Since I want to be able to tell when there is something on the reader or not the fact that when there is something I cannot get a solid signal is then a problem to me, because it seems that someone is taking the tag out, to put it back in, and out ... etc.

Do you know where that could come from?
I hope I'm not too vague.

Thomas P

**Comment by firsttris** [comment]
Hey Dermiste,

not sure if i understand correctly, but i guess i never had such an issue.

could be possible that your RFID chips are not compatible with your reader... (then you could get constant errors?

maybe its best your try to reproduce the provided examples:

https://github.com/firsttris/mfrc522-rpi/blob/master/test/read.js
https://github.com/firsttris/mfrc522-rpi/blob/master/test/write.js

Compare with the Card-Register in the README.

if your problem still persists feel free to send mail at info@teufel-it.de

best regards
Tristan

**Comment by firsttris** [comment]
Hey Thomas,
i was not able to reproduce your issue.

if i put the chip on the RFID Reader and ran `node test/read.js`
result:
https://drive.google.com/open?id=0B7mzI0TL-AbUNmVlZzVaanhYSEk

best regards
Tristan

**Comment by Dermiste** [comment]
Ok I understand now, my bad. Actually I wanted to be able to see when there is nothing, so I added some console.log here:
```
if (!response.status) {
      console.log("No card");
      return;
    }
```

I think this will do the trick, 50% of the time you should get "no card" and the rest of the time a consistant read

**Comment by firsttris** [comment]
hey you were absolutely right, the card initialization was not working correctly. we have to reset the chip at the beginning!

i changed the init() function that it is only resetting the card not the wiring pi library.

thx for your feedback.

regards
tristan
