### ISSUE TITLE
Error: Cannot find module '../build/Release/WiringPi

### ISSUE THREAD

**Issue by nelson2930** [firsttris/mfrc522-rpi#4]
I am trying to bundle up all the required modules starting at read.js into a single file called bundle.js with the browserify command: The following error is raised during operation. Any help

(venv) pi@raspberrypi:~/RFID/New $ browserify node_modules/mfrc522-rpi/test/read.js -o bundle.js
Error: Cannot find module '../build/Release/WiringPi' from '/home/pi/RFID/New/node_modules/wiringpi-node/lib'
    at /home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/pi/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

**Comment by firsttris** [comment]
Hey nelson,

i now from webpack how this works. but no xp with browserfy.

On Webpack you need to define module which contains the "native-node-modules" as external dependency.

  externals: {
    "wiringpi-node": "require('wiringpi-node')"
  }

means you can bundle it, you have to copy the dependency to your build target.

regards
Tristan

**Comment by nelson2930** [comment]
Thankyou...
As you said, i bundled the file using webpack. 
But the output file contains a require statement for wiringpi-node as below.

(function(module, exports) {
module.exports = require("wiringpi-node");
})


My aim is to make MFRC based login system from the client side and for that, I want to read cards from client side browser using the above bundled js file

Since the bundled file contains a require statement for the wiring-pi node, browser shows the following error in console

Uncaught Error: Module name "wiringpi-node" has not been loaded yet for context: _. Use require([])

Is there any option to include wiring-pi node to java-script running on the browser.

Thanks for your help

**Comment by firsttris** [comment]
In the browser its not possible but in an electron app.

clone https://github.com/electron/electron-quick-start

point "main" to your bundle.

external module needs to be copied as well

**Comment by PierreTrp** [comment]
I have the same issue but i'm not trying to bundle anything, just doing `node test/read.js` and it throw me this error : 

```
Error: Cannot find module '../build/Release/WiringPi'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/project/node_modules/wiringpi-node/lib/exports.js:1:80)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

```

Node v9.10.1
Linux raspberrypi 4.1.18-v7+

**Comment by firsttris** [comment]
@PierreTrp have you installed deps ? npm install

**Comment by jhoughjr** [comment]
I'm seeing this same thing, not bundling anything and have done nom install wiring-pi.
