### ISSUE TITLE
Example of how to write on NTAG213, if possible

### ISSUE THREAD

**Issue by txgruppi** [firsttris/mfrc522-rpi#5]
Hi,

I'm learning about the mfrc522 and I have a project that can use it with Ntag213, but it would work better if I can write on the tags.

I'm not sure mfrc522 can do this, if it don't could you just comment saying it is not possible? But if it can could you please provide a example of how to write to a NTAG213?

I've spent the last few hours trying to make it work but no success, no Google search that helped.

Thanks.

**Comment by firsttris** [comment]
thanks @musdom

**Comment by firsttris** [comment]
closing the issue, and linking this in the readme as example for NTAG213
